import type { Food } from "./types"

// Macros are per 100g unless gramsPerUnit is set (then per unit AND per 100g via gramsPerUnit).
export const SEED_FOODS: Food[] = [
  // --- Proteins ---
  {
    id: "chicken-breast",
    name: "Chicken breast (cooked)",
    emoji: "🍗",
    category: "protein",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
  },
  {
    id: "chicken-thigh",
    name: "Chicken thigh (skinless, cooked)",
    emoji: "🍗",
    category: "protein",
    calories: 209,
    protein: 26,
    carbs: 0,
    fat: 11,
  },
  {
    id: "lean-beef",
    name: "Lean beef (95/5, cooked)",
    emoji: "🥩",
    category: "protein",
    calories: 174,
    protein: 26,
    carbs: 0,
    fat: 7,
  },
  {
    id: "salmon",
    name: "Salmon (cooked)",
    emoji: "🐟",
    category: "protein",
    calories: 208,
    protein: 22,
    carbs: 0,
    fat: 13,
  },
  {
    id: "tuna-can",
    name: "Tuna (canned in water)",
    emoji: "🥫",
    category: "protein",
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
  },
  {
    id: "tilapia",
    name: "Tilapia (cooked)",
    emoji: "🐟",
    category: "protein",
    calories: 128,
    protein: 26,
    carbs: 0,
    fat: 2.7,
  },
  {
    id: "egg-whole",
    name: "Egg (whole, large)",
    emoji: "🥚",
    category: "protein",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    servingUnit: "egg",
    gramsPerUnit: 50,
  },
  {
    id: "egg-white",
    name: "Egg whites",
    emoji: "🥚",
    category: "protein",
    calories: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    servingUnit: "white",
    gramsPerUnit: 33,
  },
  {
    id: "greek-yogurt",
    name: "Greek yogurt (non-fat)",
    emoji: "🥛",
    category: "protein",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
  },
  {
    id: "cottage-cheese",
    name: "Cottage cheese (low-fat)",
    emoji: "🧀",
    category: "protein",
    calories: 81,
    protein: 11,
    carbs: 3.4,
    fat: 2.3,
  },
  {
    id: "shrimp",
    name: "Shrimp (cooked)",
    emoji: "🍤",
    category: "protein",
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
  },
  {
    id: "turkey-breast",
    name: "Turkey breast (cooked)",
    emoji: "🦃",
    category: "protein",
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
  },
  {
    id: "tofu-firm",
    name: "Tofu (firm)",
    emoji: "🍱",
    category: "protein",
    calories: 144,
    protein: 17,
    carbs: 2.8,
    fat: 8,
  },

  // --- Carbs ---
  {
    id: "white-rice",
    name: "White rice (cooked)",
    emoji: "🍚",
    category: "carb",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
  },
  {
    id: "brown-rice",
    name: "Brown rice (cooked)",
    emoji: "🍚",
    category: "carb",
    calories: 123,
    protein: 2.7,
    carbs: 26,
    fat: 1,
  },
  {
    id: "oats",
    name: "Oats (dry)",
    emoji: "🥣",
    category: "carb",
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
  },
  {
    id: "sweet-potato",
    name: "Sweet potato (cooked)",
    emoji: "🍠",
    category: "carb",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
  },
  {
    id: "white-potato",
    name: "Potato (cooked)",
    emoji: "🥔",
    category: "carb",
    calories: 87,
    protein: 1.9,
    carbs: 20,
    fat: 0.1,
  },
  {
    id: "pasta",
    name: "Pasta (cooked)",
    emoji: "🍝",
    category: "carb",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
  },
  {
    id: "whole-wheat-bread",
    name: "Whole wheat bread",
    emoji: "🍞",
    category: "carb",
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    servingUnit: "slice",
    gramsPerUnit: 30,
  },
  {
    id: "tortilla",
    name: "Flour tortilla",
    emoji: "🌯",
    category: "carb",
    calories: 304,
    protein: 8,
    carbs: 49,
    fat: 8,
    servingUnit: "tortilla",
    gramsPerUnit: 50,
  },
  {
    id: "quinoa",
    name: "Quinoa (cooked)",
    emoji: "🌾",
    category: "carb",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
  },
  {
    id: "rice-cake",
    name: "Rice cake",
    emoji: "🍘",
    category: "carb",
    calories: 387,
    protein: 8,
    carbs: 82,
    fat: 2.8,
    servingUnit: "cake",
    gramsPerUnit: 9,
  },

  // --- Fats ---
  {
    id: "almonds",
    name: "Almonds",
    emoji: "🌰",
    category: "fat",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
  },
  {
    id: "peanut-butter",
    name: "Peanut butter (natural)",
    emoji: "🥜",
    category: "fat",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
  },
  {
    id: "olive-oil",
    name: "Olive oil",
    emoji: "🫒",
    category: "fat",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
  },
  {
    id: "avocado",
    name: "Avocado",
    emoji: "🥑",
    category: "fat",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
  },
  {
    id: "walnuts",
    name: "Walnuts",
    emoji: "🌰",
    category: "fat",
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
  },

  // --- Veg ---
  {
    id: "broccoli",
    name: "Broccoli (cooked)",
    emoji: "🥦",
    category: "veg",
    calories: 35,
    protein: 2.4,
    carbs: 7.2,
    fat: 0.4,
  },
  {
    id: "spinach",
    name: "Spinach (raw)",
    emoji: "🥬",
    category: "veg",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
  },
  {
    id: "asparagus",
    name: "Asparagus (cooked)",
    emoji: "🥬",
    category: "veg",
    calories: 22,
    protein: 2.4,
    carbs: 4.1,
    fat: 0.2,
  },
  {
    id: "green-beans",
    name: "Green beans (cooked)",
    emoji: "🫘",
    category: "veg",
    calories: 35,
    protein: 1.9,
    carbs: 7.9,
    fat: 0.3,
  },
  {
    id: "bell-pepper",
    name: "Bell pepper",
    emoji: "🫑",
    category: "veg",
    calories: 26,
    protein: 1,
    carbs: 6,
    fat: 0.3,
  },
  {
    id: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    category: "veg",
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
  },

  // --- Fruit ---
  {
    id: "banana",
    name: "Banana",
    emoji: "🍌",
    category: "fruit",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    servingUnit: "banana",
    gramsPerUnit: 118,
  },
  {
    id: "apple",
    name: "Apple",
    emoji: "🍎",
    category: "fruit",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    servingUnit: "apple",
    gramsPerUnit: 182,
  },
  {
    id: "blueberries",
    name: "Blueberries",
    emoji: "🫐",
    category: "fruit",
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
  },
  {
    id: "strawberries",
    name: "Strawberries",
    emoji: "🍓",
    category: "fruit",
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
  },
  {
    id: "dates",
    name: "Dates (medjool)",
    emoji: "🌴",
    category: "fruit",
    calories: 277,
    protein: 1.8,
    carbs: 75,
    fat: 0.2,
    servingUnit: "date",
    gramsPerUnit: 24,
  },

  // --- Supplements ---
  {
    id: "whey-protein",
    name: "Whey protein",
    emoji: "🥤",
    category: "supplement",
    calories: 400,
    protein: 80,
    carbs: 10,
    fat: 5,
    servingUnit: "scoop",
    gramsPerUnit: 30,
  },
  {
    id: "casein-protein",
    name: "Casein protein",
    emoji: "🥤",
    category: "supplement",
    calories: 380,
    protein: 80,
    carbs: 8,
    fat: 3,
    servingUnit: "scoop",
    gramsPerUnit: 30,
  },
  {
    id: "creatine",
    name: "Creatine monohydrate",
    emoji: "💊",
    category: "supplement",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    servingUnit: "g",
    gramsPerUnit: 1,
  },
]
